# -*- coding: utf-8 -*-
"""Travel_Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e_DBiBSxQa0uz50Qzn83AVP_AXzCVPdS
"""

#importing required libraries
from datetime import date, timedelta
from typing import List, TypedDict
from langchain_core.tools import tool
from langchain_core.documents import Document
from langchain_google_genai import GoogleGenerativeAIEmbeddings
from langchain_community.embeddings import FakeEmbeddings
from langchain_community.vectorstores import FAISS
from langgraph.graph import StateGraph, END
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import PromptTemplate
from amadeus import Client
import requests
import pandas as pd

#API key Loading

import os

GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
OPENWEATHER_API_KEY = os.getenv("OPENWEATHER_API_KEY")
AMADEUS_CLIENT_ID = os.getenv("AMADEUS_CLIENT_ID")
AMADEUS_CLIENT_SECRET = os.getenv("AMADEUS_CLIENT_SECRET")

#Initializing API's

amadeus = Client(
    client_id=AMADEUS_CLIENT_ID,
    client_secret=AMADEUS_CLIENT_SECRET)

OPENWEATHER_API_KEY = OPENWEATHER_API_KEY

llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash-lite",
                            temperature=0.4,
                            google_api_key=GOOGLE_API_KEY)

#RAG
df = pd.read_csv("indoor_activities.csv", encoding='latin1')

if 'city,activity' in df.columns:
    df[['city', 'activity']] = df['city,activity'].str.split(',', n=1, expand=True)

    df = df.drop(columns=['city,activity'])

df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

indoor_docs = [
    Document(
        page_content=row["activity"],
        metadata={"city": row["city"].lower()}
    )
    for _, row in df.iterrows()]

embeddings = GoogleGenerativeAIEmbeddings(model="models/gemini-embedding-001", google_api_key=GOOGLE_API_KEY)
docs = indoor_docs
vectorstore = FAISS.from_documents(docs, embeddings)
retriever = vectorstore.as_retriever(search_kwargs={"k": 3})
#IF ISSUE WITH ABOVE EMBEDDINGS
#vectorstore = FAISS.from_documents(docs, FakeEmbeddings(size=32))


#Helper functions
def get_city_code(city):
    try:
        response = amadeus.reference_data.locations.get(
            keyword=city,
            subType="CITY"
        )
        return response.data[0]["iataCode"]
    except:
        return None


def get_indoor_activity(city: str):
    """Retrieve indoor activities with city → global fallback."""

    city = city.lower()
    city_activities = [
        doc.page_content for doc in indoor_docs
        if doc.metadata.get("city", "").lower() == city
    ]

    global_activities = [
        doc.page_content for doc in indoor_docs
        if doc.metadata.get("city", "").lower() == "global"
    ]

    # Priority 1: City activities
    if city_activities:
        return city_activities

    # Priority 2: Global activities (from CSV)
    if global_activities:
        return global_activities

    # Priority 3: Last resort fallback
    return [
        "Visit a museum",
        "Relax at a café",
        "Watch a movie indoors"
    ]

#Weather Tool
@tool
def get_weather(destination: str, date: date) -> str:
    """Returns weather forecast for a given date."""

    url = "http://api.openweathermap.org/data/2.5/forecast"
    params = {
        "q": destination,
        "appid": OPENWEATHER_API_KEY,
        "units": "metric"
    }

    response = requests.get(url, params=params).json()

    if "list" not in response:
        return "Weather data unavailable"

    # Match forecast date
    target = str(date)
    for entry in response["list"]:
        if entry["dt_txt"].startswith(target):
            weather = entry["weather"][0]["main"]
            return weather

    return "Weather data unavailable"

#Flight Tool

@tool
def search_flights(source: str, destination: str) -> str:
    """Search flights using Amadeus API with prices in INR."""

    try:
        origin_code = get_city_code(source.title())
        dest_code = get_city_code(destination.title())

        if not origin_code or not dest_code:
            return "Flight data unavailable."

        response = amadeus.shopping.flight_offers_search.get(
            originLocationCode=origin_code,
            destinationLocationCode=dest_code,
            departureDate=str(date.today() + timedelta(days=7)),
            adults=1,
            max=3,
            currencyCode="INR"   # 👈 ensures prices in rupees
        )

        flights = []

        for offer in response.data:
            airline = offer["validatingAirlineCodes"][0]
            price = offer["price"]["total"]
            flights.append(f"{airline} ₹{price}")

        if not flights:
            return f"No flights found from {origin_code} to {dest_code}"

        return f"Flights {origin_code} → {dest_code}: " + " | ".join(flights)

    except Exception as e:
        return f"Flight API error: {str(e)}"

#Hotel Tool
@tool
def search_hotels(destination: str) -> str:
    """Search hotels using Amadeus API."""

    try:
        city_code = get_city_code(destination)

        hotels = amadeus.reference_data.locations.hotels.by_city.get(
            cityCode=city_code
        )

        hotel_names = [hotel["name"] for hotel in hotels.data[:5]]

        return ", ".join(hotel_names).upper() if hotel_names else "No hotels found"

    except Exception as e:
        return "NA"



class TravelState(TypedDict):
    source: str
    destination: str
    start_date: date
    days: int
    itinerary: List[str]
    weather: List[str]
    flights: str
    hotels: str

planner_prompt = PromptTemplate(
    input_variables=["destination", "days"],
    template="""
You are an expert travel planner creating a friendly and realistic itinerary.

Create a {days}-day travel plan for {destination}.

Planning rules:
- Each day should include 2–3 activities.
- If an attraction requires a full day, include only one.
- Group nearby places to reduce travel time.
- Balance sightseeing, culture, food, and relaxation.
- If weather is rainy, prefer indoor activities and day should include 2–3 activities
- Use natural, friendly language.

Output format:
Day 1:
- activity
- activity
- activity

Day 2:
- activity
- activity

Rules:
- Use bullet points (-)
- No extra commentary
- Keep each bullet under 15 words
- Exactly {days} days
"""
)

#Planner Node
def planner_node(state: TravelState) -> TravelState:
    destination = state["destination"]
    days = state["days"]

    prompt = planner_prompt.format(destination=destination, days=days)
    response = llm.invoke(prompt).content.strip()

    lines = [line.strip() for line in response.split("\n") if line.strip()]

    itinerary = []
    current_day = ""

    for line in lines:
        if line.lower().startswith("day"):
            if current_day:
                itinerary.append(current_day.strip())
            current_day = line
        else:
            current_day += f" {line}"

    if current_day:
        itinerary.append(current_day.strip())

    # Ensure correct number of days
    while len(itinerary) < days:
        itinerary.append(f"Day {len(itinerary)+1}: Explore {destination}")

    state["itinerary"] = itinerary
    return state

#Weather Node
def weather_node(state: TravelState) -> TravelState:
    weather_report = []
    start_date = state["start_date"]
    days = state["days"]

    for day_offset in range(days):
        current_date = start_date + timedelta(days=day_offset)
        weather = get_weather.invoke({
            "destination": state["destination"],
            "date": current_date
        })
        weather_report.append(weather)

    state["weather"] = weather_report
    return state


#Adjustment Node
def adjust_node(state: TravelState) -> TravelState:
    destination = state["destination"]
    indoor_options = get_indoor_activity(destination)

    updated_itinerary = []

    for day_index, (activity, weather) in enumerate(zip(state["itinerary"], state["weather"])):
        # --- Normalize weather ---
        weather_lower = weather.lower()
        if "rain" in weather_lower:
            label = "Rain"
        elif "cloud" in weather_lower:
            label = "Clouds"
        elif "clear" in weather_lower or "sun" in weather_lower:
            label = "Clear"
        else:
            label = "NA"

        # --- Extract clean activity text ---
        activity_text = activity.split(":", 1)[-1].strip()

        # --- Rain → indoor replacement ---
        if label == "Rain":
            indoor = (
                indoor_options[day_index % len(indoor_options)]
                if indoor_options else f"Indoor activities in {destination.title()}"
            )
            final_text = indoor
        else:
            final_text = activity_text

        updated_itinerary.append(f"Day {day_index+1}: {final_text}")

    state["itinerary"] = updated_itinerary
    return state

#Flight & Hotel Node


def flight_node(state):
    state["flights"] = search_flights.invoke({
        "source": state["source"],
        "destination": state["destination"]
    })
    return state


def hotel_node(state):
    state["hotels"] = search_hotels.invoke({
        "destination": state["destination"]
    })
    return state


#Finalize Node


def finalize_node(state: TravelState) -> dict:
    return {
        "source": state["source"].title(),
        "destination": state["destination"].title(),
        "days": state["days"],
        "start_date": str(state["start_date"]),
        "itinerary": state["itinerary"],
        "flights": state.get("flights", "NA"),
        "hotels": state.get("hotels", "NA")
    }

#Langgraph Workflow

graph = StateGraph(TravelState)

# Add nodes
graph.add_node("planner", planner_node)
graph.add_node("weather", weather_node)
graph.add_node("adjust", adjust_node)

graph.add_node("flights", flight_node)
graph.add_node("hotels", hotel_node)
graph.add_node("finalize", finalize_node)

# Entry point
graph.set_entry_point("planner")

# Flow
graph.add_edge("planner", "weather")
graph.add_edge("weather", "adjust")
graph.add_edge("adjust", "flights")
graph.add_edge("flights", "hotels")
graph.add_edge("hotels", "finalize")


# Compile
app = graph.compile()

